# Colors Configuration
# This file contains a default color scheme
# The Catppuccin theme will override these when imported

[colors]
# Draw bold text with bright colors instead of bold font
draw_bold_text_with_bright_colors = true

# Transparent background colors
transparent_background_colors = false

# Primary colors
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

# Cursor colors
[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

# Vi mode cursor colors
[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

# Search colors
[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

# Selection colors
[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

# Normal colors
[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

# Bright colors
[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

# Dim colors
[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

# Footer bar (used by search regex input)
[colors.footer_bar]
background = "#a6adc8"
foreground = "#1e1e2e"

# Hints
[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

# Line indicator
[colors.line_indicator]
foreground = "None"
background = "None"